# Generated by Django 6.0.2 on 2026-02-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usuario_categoria_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'En Préstamo'), ('mantenimiento', 'En Mantenimiento'), ('baja', 'Dado de Baja')], default='disponible', max_length=20),
        ),
    ]
