# Generated by Django 6.0.2 on 2026-03-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_instrumento_cantidad_instrumento_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('enuso', 'En uso'), ('reparacion', 'Reparación')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
