# Generated by Django 6.0.2 on 2026-03-10 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_prestamo_estado_alter_prestamo_fecha_prestamo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialestadoinstrumento',
            name='estado',
        ),
        migrations.AddField(
            model_name='historialestadoinstrumento',
            name='estado_anterior',
            field=models.CharField(blank=True, choices=[('disponible', 'Disponible'), ('prestado', 'En Préstamo'), ('mantenimiento', 'En Mantenimiento'), ('baja', 'Dado de Baja')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='historialestadoinstrumento',
            name='estado_nuevo',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'En Préstamo'), ('mantenimiento', 'En Mantenimiento'), ('baja', 'Dado de Baja')], default='disponible', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialestadoinstrumento',
            name='tipo_movimiento',
            field=models.CharField(choices=[('registro', 'Registro de instrumento'), ('prestamo', 'Préstamo de instrumento'), ('devolucion', 'Devolución de instrumento'), ('reparacion', 'Envío a reparación'), ('baja', 'Baja de instrumento'), ('cambio_estado', 'Cambio manual de estado')], default='registro', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialestadoinstrumento',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_movimientos', to='api.instrumento'),
        ),
    ]
